server:
  port: 8190

# Настройки Server Discovery
eureka:
  instance:
    appname: product
  client:
    serviceUrl:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE}
    instance:
      preferIpAddress: true

# Настройки базы данных
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/product?currentSchema=application
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

# Настройки JWT аутентификации
jwt:
  secret: c29rb2xvdg==